/* Automatic generated by DeviceToClazz */

package xiaomi.com.projection.device.control;

import android.os.Parcel;

import upnps.api.manager.ctrlpoint.device.AbstractDevice;
import upnp.typedef.device.Device;
import upnp.typedef.device.Service;

public class MediaDevice extends AbstractDevice {

    private MediaRenderingControl _MediaRenderingControl;
    private StreamTransport _StreamTransport;

    public MediaRenderingControl getMediaRenderingControl() {
        return _MediaRenderingControl;
    }
    public StreamTransport getStreamTransport() {
        return _StreamTransport;
    }

    private static final Object classLock = MediaDevice.class;
    private static final String DEVICE_TYPE = "MediaDevice";
    private static final String ID_MediaRenderingControl = "urn:upnp-org:serviceId:MediaRenderingControl";
    private static final String ID_StreamTransport = "urn:upnp-org:serviceId:StreamTransport";

    public static MediaDevice create(Device device) {
        synchronized (classLock) {
            MediaDevice thiz = new MediaDevice(device);
                
            do {
                if (! DEVICE_TYPE.equals(device.getDeviceType().getName())) {
                    thiz = null;
                    break;
                }

                if (! thiz.initialize()) {
                    thiz = null;
                    break;
                }
            } while (false);

            return thiz;
        }
    }

    private MediaDevice(Device device) {
        this.device = device;
    }

    private boolean initialize() {
        boolean ret = false;

        do {
            Service theMediaRenderingControl = device.getService(ID_MediaRenderingControl);
            if (theMediaRenderingControl == null) {
                break;
            }

            Service theStreamTransport = device.getService(ID_StreamTransport);
            if (theStreamTransport == null) {
                break;
            }

            _MediaRenderingControl = new MediaRenderingControl(theMediaRenderingControl);
            _StreamTransport = new StreamTransport(theStreamTransport);

            ret = true;
        } while (false);

        return ret;
    }

    public static final Creator<MediaDevice> CREATOR = new Creator<MediaDevice>() {

        @Override
        public MediaDevice createFromParcel(Parcel in) {
            return new MediaDevice(in);
        }

        @Override
        public MediaDevice[] newArray(int size) {
            return new MediaDevice[size];
         }
    };

    private MediaDevice(Parcel in) {
        readFromParcel(in);
    }

    public void readFromParcel(Parcel in) {
        device = in.readParcelable(Device.class.getClassLoader());
        initialize();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeParcelable(device, flags);
    }
}
