/* Automatic generated by DeviceToClazz */

package com.xiaomi.upnp.examples.projection.source.device.source.host;

import android.content.Context;
import android.util.Log;

import java.util.HashMap;
import java.util.Map;

import upnp.typedef.error.UpnpError;
import upnp.typedef.device.Device;
import upnp.typedef.device.invocation.ActionInfo;
import upnp.typedef.exception.UpnpException;

import upnps.manager.UpnpManager;
import upnps.manager.handler.MyActionHandler;
import upnps.manager.handler.MyCompletionHandler;
import upnps.manager.host.config.DeviceConfig;
import upnps.manager.host.ServiceStub;

public class SourceDevice implements MyActionHandler {

    private static final String TAG = "SourceDevice";

    /**
     * deviceType & serviceType
     */
    public static final String DEVICE_TYPE = "SourceDevice";
    public static final String SERVICE_MediaProjection = "MediaProjection";
    public static final String SERVICE_SessionManager = "SessionManager";

    /**
     * serviceId
     */
    private static final String ID_MediaProjection = "urn:upnp-org:serviceId:MediaProjection";
    private static final String ID_SessionManager = "urn:upnp-org:serviceId:SessionManager";

    /**
     * device & service handler;
     */

    private Device _device;
    private Map<String, ServiceStub> _services = new HashMap<String, ServiceStub>();

    public SourceDevice(Context context, DeviceConfig config) throws UpnpException {
        _device = config.build(context);
        _services.put(ID_MediaProjection, new MediaProjection(_device.getService(ID_MediaProjection)));
        _services.put(ID_SessionManager, new SessionManager(_device.getService(ID_SessionManager)));
    }

    public String getDeviceId() {
        return _device.getDeviceId();
    }

    public void start(MyCompletionHandler handler) throws UpnpException {
        UpnpManager.getHost().register(_device, handler, this);
    }

    public void stop(MyCompletionHandler handler) throws UpnpException {
        UpnpManager.getHost().unregister(_device, handler);
    }

    @Override
    public UpnpError onAction(ActionInfo info) {
        ServiceStub handler = _services.get(info.getServiceId());
        if (handler == null) {
            Log.e(TAG, "service not found: " + info.getServiceId());
            return UpnpError.UPNP_INTERNAL_ERROR;
        }

        return handler.onAction(info);
    }

    public MediaProjection getMediaProjection() {
        return (MediaProjection)_services.get(ID_MediaProjection);
    }

    public SessionManager getSessionManager() {
        return (SessionManager)_services.get(ID_SessionManager);
    }

}
